services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./backend/cartas
      dockerfile: src/main/docker/Dockerfile
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8080:8080'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cartas
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    restart: on-failure

  front:
    build:
      context: ./frontend/angularfront
      dockerfile: ../Dockerfile
    container_name: frontend
    volumes:
      - ./frontend/angularfront:/app
      - /app/node_modules
    ports:
      - '4200:4200'
    stdin_open: true
    tty: true

          
  db:
    image: 'postgres:16-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=cartas
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./frontend/angularfront/src/app/images:/images 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d cartas"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: