spring.application.name=cartas
server.port=8080

management.endpoints.web.exposure.include=health,info,mappings
management.endpoints.web.base-path=/actuator



spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


spring.datasource.url=jdbc:postgresql://db:5432/cartas?currentSchema=schema
spring.datasource.username=root
spring.datasource.password=root
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql   
spring.sql.init.continue-on-error=true

