-- Por ahora insertamos las imágenes manualmente, estamos planeando alguna manera de automatizarlo
INSERT INTO imagenes(nombre,data) VALUES 
('logoInvizimals',pg_read_binary_file('/images/logosMarcas/invizimals.png')),
('logoLorcana',pg_read_binary_file('/images/logosMarcas/lorcanalogo.png')),
('logoMagic',pg_read_binary_file('/images/logosMarcas/Magic-The-Gathering-logo.png')),
('logoMarvelC',pg_read_binary_file('/images/logosMarcas/marvelChampions.png')),
('logoPokTCG',pg_read_binary_file('/images/logosMarcas/Pokémon_Trading_Card_Game_logo.svg.png')),
('logoYugioh',pg_read_binary_file('/images/logosMarcas/Yugioh_Logo.webp')),
('logoMulligan',pg_read_binary_file('/images/logoMulligan.png')),
('CharizardOriginal',pg_read_binary_file('/images/cartas/chariz.png')),
('Blue-Eyes White Dragon',pg_read_binary_file('/images/cartas/bewd.jpg')),
('Pot Of Greed',pg_read_binary_file('/images/cartas/PotOfGreed.jpg')),
('PikachuOriginal',pg_read_binary_file('/images/cartas/PikachuOG.jpg')),
('Forest',pg_read_binary_file('/images/cartas/ForestMtg.jpg')),
('Swamp',pg_read_binary_file('/images/cartas/Swamp.jpg')),
('Fanbot',pg_read_binary_file('/images/cartas/Fanbot.jpg')),
('Tony Stark',pg_read_binary_file('/images/cartas/tony.png')),
('Elsa',pg_read_binary_file('/images/cartas/Elsa.png')),
('Dark Magician',pg_read_binary_file('/images/cartas/DarkMagician.jpg')),
('Monster Reborn', pg_read_binary_file('/images/cartas/MonsterReborn.jpg')),
('Sol Ring', pg_read_binary_file('/images/cartas/SolRing.jpg')),
('Lightning Bolt', pg_read_binary_file('/images/cartas/LightningBolt.jpg')),
('Mewtwo', pg_read_binary_file('/images/cartas/Mewtwo.jpg')),
('Gengar', pg_read_binary_file('/images/cartas/Gengar.jpg')),
('Tepig', pg_read_binary_file('/images/cartas/Tepig.jpg')) -- he is a god boi
ON CONFLICT (nombre) DO NOTHING;

INSERT INTO carta (nombreCard, descripcion, coleccion, empresa, idimg) 
VALUES 
('Blue-Eyes White Dragon', 'Este dragón legendario es una poderos máquina de destrucción. Virtualmente invencible, pocos han visto esta asombrosa criatura y vivido para contarlo.', 'OG', 'YUGIOH',
(SELECT idimg FROM imagenes WHERE nombre = 'Blue-Eyes White Dragon')),
('Pot of Greed', 'Roba 2 cartas.', 'OG', 'YUGIOH', 
(SELECT idimg FROM imagenes WHERE nombre = 'Pot Of Greed')),
('Charizard', 'La original carta de Charizard de 1995', 'OG 1995', 'POKEMON', 
(SELECT idimg FROM imagenes WHERE nombre = 'CharizardOriginal')),
('Pikachu', 'La original carta de 1995', 'OG 1995', 'POKEMON', 
(SELECT idimg FROM imagenes WHERE nombre = 'PikachuOriginal')),
('Forest', 'Tierra Básica - Mana verde', 'Basic Set', 'MAGIC', 
(SELECT idimg FROM imagenes WHERE nombre = 'Forest')),
('Swamp', 'Tierra Básica - Mana Negro', 'Basic Set', 'MAGIC', 
(SELECT idimg FROM imagenes WHERE nombre = 'Swamp')),
('Fanbot', 'La velocidad es la principal ventaja de Fanbot. Gracias a su facilidad para desplazarse, busca la sorpresa y no la fuerza. Antes de atacar, examina a los rivales con un ojo cámara telescópico y se planta ante ellos en un santiamén.', 'Invizimals: The Resistance', 'INVIZIMALS', 
(SELECT idimg FROM imagenes WHERE nombre = 'Fanbot')),
('Elsa', 'Recreada con tinta mágica, Elsa se encontró en un nuevo mundo. Desafortunadamente, hielo funciona de igual manera en todos lados', '1ª Ronda', 'LORCANA', 
(SELECT idimg FROM imagenes WHERE nombre = 'Elsa')),
('Tony Stark', 'Obviamemente no hago esto por dinero...', '1er Set', 'MARVELC', 
(SELECT idimg FROM imagenes WHERE nombre = 'Tony Stark')),
('Dark Magician', 'El mago definitivo en términos de ataque y defensa.', 'Legend of Blue Eyes', 'YUGIOH',
(SELECT idimg FROM imagenes WHERE nombre = 'Dark Magician')),
('Monster Reborn', 'Selecciona 1 monstruo en cualquier Cementerio; invócalo de Modo Especial.', 'LOB', 'YUGIOH',
(SELECT idimg FROM imagenes WHERE nombre = 'Monster Reborn')),
('Sol Ring', 'Añade 2 manás incoloros a tu reserva de maná.', 'Commander', 'MAGIC',
(SELECT idimg FROM imagenes WHERE nombre = 'Sol Ring')),
('Lightning Bolt', 'El Relámpago hace 3 puntos de daño a cualquier objetivo.', 'Alpha', 'MAGIC',
(SELECT idimg FROM imagenes WHERE nombre = 'Lightning Bolt')),
('Mewtwo', 'Fue creado por un científico tras años de horribles experimentos de ingeniería genética.', 'Base Set', 'POKEMON',
(SELECT idimg FROM imagenes WHERE nombre = 'Mewtwo')),
('Gengar', 'Al amparo de la oscuridad, acecha a sus presas. Cuidado, es muy peligroso.', 'Fossil', 'POKEMON',
(SELECT idimg FROM imagenes WHERE nombre = 'Gengar')),
('Tepig', 'Tepig es un Pokémon de tipo fuego. Es el Pokémon inicial de tipo fuego de la región de Unova.', 'Black & White', 'POKEMON',
(SELECT idimg FROM imagenes WHERE nombre = 'Tepig'))
ON CONFLICT (nombreCard) DO NOTHING;